gesdinet_jwt_refresh_token:
    path:       /auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

api_login_check:
    path: /auth/login

api_auth_me:
    path: /auth/me
    controller: App\Symfony\Controller\AuthMeAction
