services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\:
        resource: '../features/*'

    App\Tests\Context\ApiPlatformContext:
        arguments:
            $client: '@test.client'
#            $doctrine: '@Doctrine\Common\Persistence\ManagerRegistry'
        
    Symfony\Component\HttpClient\MockHttpClient: ~

    App\Tests\Fixtures\HubStub:
        decorates: mercure.hub.default
