services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\:
        resource: '../features/*'
        
    App\Tests\Stub\HubStub:
        decorates: mercure.hub.default

    Symfony\Component\BrowserKit\AbstractBrowser:
        alias: 'test.client'

    Fidry\AliceDataFixtures\LoaderInterface:
        alias: 'fidry_alice_data_fixtures.doctrine.persister_loader'

    Nelmio\Alice\FileLoaderInterface:
        alias: 'nelmio_alice.file_loader.simple'
