name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Api Tests
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist
        
      - name: Generate JWT keypair
        run: bin/console lexik:jwt:generate-keypair
        
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration phpstan.neon src
        
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run
        
      - name: Run Behat
        run: vendor/bin/behatt --config behat.yml
        
      - name: Run Doctrine Schema Validator
        run: bin/console doctrine:schema:validate --skip-sync
