name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Api Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    defaults: 
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist
        
      - name: Generate JWT keypair
        run: bin/console lexik:jwt:generate-keypair

      - name: Prepare database
        run: bin/console doctrine:migrations:migrate --no-interaction
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8

      - name: Run PHPStan
        run: bin/phpstan analyse --configuration phpstan.neon src

      - name: Run PHP-CS-Fixer
        run: bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run

      - name: Run PHPSpec
        run: bin/phpspec run
        
      - name: Run Behat
        run: bin/behat --config behat.yml
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8

      - name: Run Doctrine Schema Validator
        run: bin/console doctrine:schema:validate --skip-sync
